#!/bin/bash
#$ -t 393-610
#$ -S /bin/bash
#$ -V
#$ -l h_vmem=4G
#$ -wd /home/chadavis/catalog_creation/astro_image_processing/LRG/
#$ -o /home/chadavis/catalog_creation/astro_image_processing/LRG/output/
#$ -e /home/chadavis/catalog_creation/astro_image_processing/LRG/output/
#$ -N casj
#$ -l low
#$ -l h="node01|node02|node03|node04|node05|node06|node07|node08|node09|node10|node11|node12|node13|node14|node15|node16|node17|node18|node19|node20|node21|node22"
#$ -tc 1

/home/chadavis/catalog_creation/astro_image_processing/LRG/casjobs.py $SGE_TASK_ID 